# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7008c1c43febdb644e816f3ffd7182d01fb5509afb078d61ef42241d49993426f5593bcf29d4adcf3ac063776660af7a37a92dfaa1ccc16f165325ace63958a

test:
  secret_key_base: 0ef8b5032ccfcb53c6bc702d3bde07ecff129f1746ec31366a529c51107d21978fd7e3d4a118f92458b78f7ffcb35b99b7ca61aa5bef95e669af4017141f1f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
